/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.maksutapa;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 20128509
 */
public class Maksutapa extends javax.swing.JFrame {

    /**
     * Creates new form Maksutapa
     */
    public Maksutapa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupMaksutapa = new javax.swing.ButtonGroup();
        jRadioVisa = new javax.swing.JRadioButton();
        jRadioOP = new javax.swing.JRadioButton();
        jRadioKateinen = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtMaara = new javax.swing.JTextField();
        jtxtHinta = new javax.swing.JTextField();
        jbtnLaske = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtLoppusumma = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btngroupMaksutapa.add(jRadioVisa);
        jRadioVisa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioVisa.setText("Visa: -1% alennus");
        jRadioVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioVisaActionPerformed(evt);
            }
        });

        btngroupMaksutapa.add(jRadioOP);
        jRadioOP.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioOP.setText("OP tilisirto kertamaksulla: -2% alennus");

        btngroupMaksutapa.add(jRadioKateinen);
        jRadioKateinen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioKateinen.setText("Käteinen +2% hintaa lisää");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Määritä tuotteiden määrä, hinta ja valitse maksutapa, niin ohjelma laskee tilauksen loppusumman.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Määrä:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Hinta/kpl:");

        jtxtMaara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMaaraActionPerformed(evt);
            }
        });

        jtxtHinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHintaActionPerformed(evt);
            }
        });

        jbtnLaske.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnLaske.setText("Laske");
        jbtnLaske.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLaskeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tilauksen loppusumma:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnLaske)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxtLoppusumma))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(61, 61, 61)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioKateinen)
                                    .addComponent(jRadioOP)
                                    .addComponent(jRadioVisa))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jRadioVisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioOP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioKateinen)
                .addGap(18, 18, 18)
                .addComponent(jbtnLaske)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtLoppusumma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtMaaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMaaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMaaraActionPerformed

    private void jbtnLaskeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLaskeActionPerformed
        // TODO add your handling code here:
       float maara,hinta;
      
       try {
            maara = Float.parseFloat(jtxtMaara.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita, kiitos. Korjaa jälkesi. virhe: "+e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;    
        }
       
        try {
            hinta = Float.parseFloat(jtxtHinta.getText());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita, kiitos. Korjaa jälkesi. virhe: "+e.getMessage(), "Virhe", JOptionPane.ERROR_MESSAGE);
            return;    
        }
     jRadioVisa.setActionCommand("Visa");
     jRadioOP.setActionCommand("OP");
     jRadioKateinen.setActionCommand("Käteinen");
    
    
     jtxtLoppusumma.setText("Valitsit maksutavaksi: " + btngroupMaksutapa.getSelection().getActionCommand());
   
     
        
    }//GEN-LAST:event_jbtnLaskeActionPerformed

    private void jtxtHintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHintaActionPerformed

    private void jRadioVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioVisaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jRadioVisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maksutapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maksutapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maksutapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maksutapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maksutapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroupMaksutapa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioKateinen;
    private javax.swing.JRadioButton jRadioOP;
    private javax.swing.JRadioButton jRadioVisa;
    private javax.swing.JButton jbtnLaske;
    private javax.swing.JTextField jtxtHinta;
    private javax.swing.JTextField jtxtLoppusumma;
    private javax.swing.JTextField jtxtMaara;
    // End of variables declaration//GEN-END:variables
}
